### ISSUE TITLE
Add the ability to change the api key

### ISSUE THREAD

**Issue by yura999999999** [nvlad/tinypng-optimizer#10]
Good day!

First of all, I would like to thank you for working on the plugin.

It would be great if there was the possibility of changing the API key for tinypng

Best regards,
Yury Y.

**Comment by nvlad** [comment]
Hi! 
Thx for your feedback!

For change TinyPNG API key open IDE settings -> Tools -> TinyPNG Image Optimize and paste new key in API Key field.

**Comment by yura999999999** [comment]
Indeed, there is an opportunity to change.

Thank! Close!

**Comment by yura999999999** [comment]
Indeed, there is an opportunity to change.

Thank! Close!
